DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todolist;
DROP TABLE IF EXISTS todoitem;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);


CREATE TABLE todolist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE todoitem (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    list_id INTEGER NOT NULL,
    complete BOOLEAN,
    body TEXT NOT NULL,
    FOREIGN KEY (list_id) REFERENCES todolist (id)
);